### ISSUE TITLE
Virtualbox 7.0.14 on 6.7.1-zabbly+ #ubuntu22.04 spams to console log

### ISSUE THREAD

**Issue by teckau** [zabbly/linux#13]
Anything I can do to stop this? Seems to be kernel related and seems to have appeared just with the last update to 6.7?!

[  259.819851] ================================================================================
[  259.819856] UBSAN: array-index-out-of-bounds in /tmp/vbox.0/r0drv/linux/memobj-r0drv-linux.c:903:37
[  259.819858] index 511 is out of range for type 'page *[1]'
[  259.819860] CPU: 6 PID: 3207 Comm: EMT-0 Tainted: G        W  OE      6.7.1-zabbly+ #ubuntu22.04
[  259.819862] Hardware name: To Be Filled By O.E.M. N7 Z590/N7 Z590, BIOS P1.50 10/20/2021
[  259.819863] Call Trace:
[  259.819864]  <TASK>
[  259.819867]  dump_stack_lvl+0x48/0x70
[  259.819876]  dump_stack+0x10/0x20
[  259.819878]  __ubsan_handle_out_of_bounds+0xa2/0x100
[  259.819881]  ? alloc_pages+0x5e/0xd0
[  259.819885]  rtR0MemObjNativeAllocLarge+0x219/0x250 [vboxdrv]
[  259.819924]  VBoxHost_RTR0MemObjAllocLargeTag+0x6a/0xe0 [vboxdrv]
[  259.819952]  ? try_to_wake_up+0x271/0x6d0
[  259.819954]  ? __mod_timer+0x292/0x430
[  259.819957]  ? __wake_up_common+0x78/0xb0
[  259.819960]  ? rtR0MemFree+0x27/0x40 [vboxdrv]
[  259.819981]  ? supdrvIOCtlFast+0x5a/0xf0 [vboxdrv]
[  259.820000]  ? VBoxDrvLinuxIOCtl_7_0_14+0x66/0x260 [vboxdrv]
[  259.820016]  ? __fget_light+0xa0/0x150
[  259.820019]  ? __x64_sys_ioctl+0x9d/0xe0
[  259.820022]  ? do_syscall_64+0x5c/0xf0
[  259.820025]  ? do_syscall_64+0x6b/0xf0
[  259.820027]  ? syscall_exit_to_user_mode+0x38/0x60
[  259.820030]  ? do_syscall_64+0x6b/0xf0
[  259.820032]  ? syscall_exit_to_user_mode+0x38/0x60
[  259.820034]  ? do_syscall_64+0x6b/0xf0
[  259.820036]  ? entry_SYSCALL_64_after_hwframe+0x6e/0x76
[  259.820040]  </TASK>
[  259.820049] ================================================================================

**Comment by stgraber** [comment]
That should be reported to the VirtualBox folks if they haven't already fixed this.

The kernel is basically telling you that there is a potential bug around memory management in that driver.

As the VirtualBox driver is an external driver, likely using DKMS and not something that's part of the kernel itself, it's not something that will get fixed through a new kernel update.
