### ISSUE TITLE
No ZFS modul?

### ISSUE THREAD

**Issue by MrGlasspoole** [zabbly/linux#14]
Hi,

I'm completely new to Incus.
I installed this Kernel in Debian 12 because of Incus and the Incus page does recommend ZFS.

But
`~$ incus storage create MyPool zfs size=30GiB`
gives me
`Error: Error loading "zfs" module: Failed to run: modprobe -b zfs: exit status 1 (modprobe: FATAL: Module zfs not found in directory /lib/modules/6.7.1-zabbly+)`

**Comment by stgraber** [comment]
There's a section about that in the instructions of this very repository that sends you to the separate zfs repository.

https://github.com/zabbly/linux?tab=readme-ov-file#zfs-availability
