### ISSUE TITLE
6.7.3 kernel + nvidia incompatibility: ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol ‘__rcu_read_lock’

### ISSUE THREAD

**Issue by lazystone** [zabbly/linux#15]
Sorry, I'm a complete noob in those questions, so I'm not sure if zabbly maintainers should/can do anything about this issue.

Maybe more like FYI:

https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908

**Comment by stgraber** [comment]
Yeah, it's basically NVIDIA using kernel internal functions which they aren't supposed to given that their module isn't GPL.

I see someone posted a workaround in that thread and nvidia will likely be posting a new driver soon as that same change is going into a lot of other kernel versions.
