### ISSUE TITLE
Error: Driver 'pcspkr' is already registered, aborting

### ISSUE THREAD

**Issue by rudiservo** [zabbly/linux#17]
Hi, don't know if this is normal

I got this error with kernel 6.8.2-zabbly+

`Error: Driver 'pcspkr' is already registered, aborting`

The hardware is an old Asus eeepc 1215B, AMD E-350.

The OS is plain Debian 12, only added zabbly kernel and incus.

I know it's old, that why I test stuff on it.

Anyway blacklist pcspkr solved the error.

Also no login prompt shows up in the screen, just blank, I can ssh into the machine just fine tough.

Thanks for the repo.

**Comment by stgraber** [comment]
Sounds like the error was coming from two consecutive attempts to modprobe the same driver, this should be harmless.
