### ISSUE TITLE
v4l2loopback module is missing

### ISSUE THREAD

**Issue by slr** [zabbly/linux#18]
haven't use v4l2loopback about two months and now when I tried to modprobe it with most recent kernels (both 6.8.7 and 6.8.6) I see it's gone

**Comment by stgraber** [comment]
This is an out of tree module, you need to rebuild it every time you update your kernel.

It's also possible that you need to fetch a newer version of the code from upstream as the Linux kernel module ABI changes between kernel versions.

**Comment by slr** [comment]
ok, thanks
