### ISSUE TITLE
Enable CONFIG_DRM_LOAD_EDID_FIRMWARE

### ISSUE THREAD

**Issue by bai-yi-bai** [zabbly/linux#21]
Hi,

Installing 6.9.6-zabbly+ fixed my Intel AX210 CVNI Wi-Fi drivers on my n100 machine, thank you!

I'm trying to fix a incorrect EDID for a projector which doesn't contain the audio block data.

I was able to get audio output working using the information from [https://wiki.archlinux.org/title/Kernel_mode_setting#Forcing_modes_and_EDID](Arch Wiki - Kernel Mode - Force Modes and EDID) by creating a modified EDID, rebuilding initramfs, adding 
`GRUB_CMDLINE_LINUX_DEFAULT="quiet drm.edid_firmware=edid/projector-w-sound.bin"` to grub and copying the EDID to `echo edid/projector-w-sound.bin > /sys/module/drm/parameters/edid_firmware`.

On a fresh reboot, I have no sound. There are two fixes, 

1. Manually unplugging and re-plugging in the HDMI cable
2. Run `xset dpms force off; xset dpms force on` from KDE; I've set this as a startup script.

Upon investigation, if I echo echo `'eld_valid 1' | tee /proc/asound/card0/eld#2.4`, Pulse Audio seems to load the faulty EDID back over HDMI, which is missing this information I added:
```
sad_count               1
sad0_coding_type        [0x1] LPCM
sad0_channels           2
sad0_rates              [0xe0] 32000 44100 48000
sad0_bits               [0xe0000] 16 20 24
```

According to the Arch Wiki post, there is a new CONFIG_DRM_LOAD_EDID_FIRMWARE kernel flag.
[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89ac522d4507126d353834973ddbbf7b6acfdeef](drm/edid/firmware: Remove built-in EDIDs) 

I don't know if this will solve my no sound at boot problem, I could be totally wrong here, but I did a search of the repository and I'm not sure whether this is enabled. I'm not sure where the .conf files are held.

Thank you!

**Comment by stgraber** [comment]
`CONFIG_DRM_LOAD_EDID_FIRMWARE` is already set to `y` in the zabbly kernel.

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ grep CONFIG_DRM_LOAD_EDID_FIRMWARE /boot/config-6.9.7-zabbly+ 
CONFIG_DRM_LOAD_EDID_FIRMWARE=y
```
