### ISSUE TITLE
respository down?

### ISSUE THREAD

**Issue by wingedonezero** [zabbly/linux#23]
It looks like the repository is having a 503 Service Unavailable
No server is available to handle this request. 
![Screenshot_20240730_013926](https://github.com/user-attachments/assets/bc657dea-e26b-42a5-9e8c-f281da6fab92)

**Comment by stgraber** [comment]
The latest ceph packages had a missing dependency which caused a few minutes of outage during the usual weekly rolling updates+reboots.
