### ISSUE TITLE
Debian 12 Kernel v10.0.5 boot error

### ISSUE THREAD

**Issue by arunnabraham** [zabbly/linux#24]
![image](https://github.com/user-attachments/assets/5830afb1-f383-468f-a77e-af35c6cdcf41)

I find this after rebooting from latest update

**Comment by stgraber** [comment]
Hmm, I'd boot back on the previous kernel and try to reinstall the 6.10.5.

I'm running 6.10.5 here on Debian 12 and also on an AMD system using amdgpu, so if there was something generally broken with the kernel or the amdgpu module that ships with it, both of my own systems would fail to boot.

**Comment by arunnabraham** [comment]
Well to make it clear I am using sid. It was working fine till 6.10.4. Dont know how to specifically reinstall that

**Comment by arunnabraham** [comment]
I did run the re install. Yet the result is same.

**Comment by stgraber** [comment]
The errors suggest either missing modules in the initrd (you could try to compare the 6.10.4 to 6.10.5 by using lsinitramfs) or that the modules.dep file in the initrd is out of whack.

It may be a good idea to look at what other packages got updated recently on your system.

**Comment by stgraber** [comment]
```
root@sid:~# uname -a
Linux sid 6.10.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.6-1 (2024-08-19) x86_64 GNU/Linux
root@sid:~# cat /etc/apt/sources.list
# Generated by distrobuilder
deb http://deb.debian.org/debian sid main
root@sid:~# cat /etc/debian_version 
trixie/sid
root@sid:~# apt update
Hit:1 http://deb.debian.org/debian sid InRelease
Hit:2 https://pkgs.zabbly.com/kernel/stable bookworm InRelease
All packages are up to date.                   
root@sid:~# 
```

**Comment by stgraber** [comment]
```
root@sid:~# uname -a
Linux sid 6.10.5-zabbly+ #debian12 SMP PREEMPT_DYNAMIC Thu Aug 15 23:02:18 UTC 2024 x86_64 GNU/Linux
root@sid:~# cat /etc/debian_version 
trixie/sid
root@sid:~# cat /etc/apt/sources.list
deb http://deb.debian.org/debian sid main
root@sid:~# 
```

**Comment by stgraber** [comment]
I'm closing this issue because the Zabbly package repository is only supported on stable Debian releases, so Debian 11 or 12.

Running on testing or sid is at your own risk and sid is much too unstable to be able to really do any debugging on. It's also worth noting that sid currently has a Debian 6.10.6 kernel in its repository, having both Debian and my kernel builds of the same kernel installed on the same system could definitely cause this kind of issue.
