### ISSUE TITLE
6.10.6 not available for ubuntu 22.04 arm64

### ISSUE THREAD

**Issue by vincent1990** [zabbly/linux#25]
Hi, is there an issue with 6.10.6 release? I think it was released as I see commits on github but when I check for update on my server, it shows nothing. I am still on linux-headers-6.10.5-zabbly+. I wish there was a website for new kernel releases as those could then be installed manually.

**Comment by stgraber** [comment]
It's been stuck in testing so hasn't been released yet, 6.10.7 is also right around the corner so we may end up skipping .6.

**Comment by stgraber** [comment]
It's now been published
