### ISSUE TITLE
UBSAN: array-index-out-of-bounds in drivers/scsi/mp3sas-scsih.c

### ISSUE THREAD

**Issue by Tomxtal** [zabbly/linux#3]
Debian 12 (bookworm)
Kernel: 6.5.1-zabbly+
Host: Dell Precision T7610 (00)

At boot screen message UBSAN: array-index-out-of-bounds in drivers/scsi/mp3sas-scsih.c
index 1 is out of range for type 'MP12_SAS_IO_UNITO_PHY_DATA [1]'

Tom

**Comment by stgraber** [comment]
Is that having any impact other than the extra logged message?

The 6.5 kernel comes with additional UBSAN checks like this one which is causing a number of drivers to now trigger warnings.
Those will be slowly processed by their respective maintainers. I dealt with one of those when refreshing the ZFS DKMS packages so I expect that we'll see those pop up in a few drivers for a little while until they're all squashed.

**Comment by stgraber** [comment]
https://lore.kernel.org/lkml/20230725161331.27481-1-james@equiv.tech/ is a current attempt at resolving the warnings though the fix still needs some work.

**Comment by Tomxtal** [comment]
Thanks Stgraber
Just to let you know there is no other impact on my system warnings.

Tom

**Comment by stgraber** [comment]
Good to hear, clearly it's something that's being worked on, hopefully the 6.6 kernel will contain a suitable fix and if that happens quickly enough we may even see it backported to one of the 6.5 bugfix releases.

**Comment by stgraber** [comment]
Closing as something that will be resolved in upstream linux.
