### ISSUE TITLE
enable BTF

### ISSUE THREAD

**Issue by szuecs** [zabbly/linux#5]
Would it be possible to enable or add as module the BTF config:
CONFIG_DEBUG_INFO_BTF
CONFIG_PAHOLE_HAS_SPLIT_BTF
CONFIG_DEBUG_INFO_BTF_MODULES

**Comment by stgraber** [comment]
That would require the entire kernel to be built with CONFIG_DEBUG_INFO enabled which it currently doesn't have. Doing this was more than tripling the kernel build time which wasn't ideal.

**Comment by stgraber** [comment]
I did a resync with the Ubuntu kernel config now which includes re-enabling debugging, we'll see exactly what the build time impact is.

**Comment by stgraber** [comment]
I think I did enough tweaking that we should be able to get the BTF stuff up in the next kernel update (6.6.2).

It requires building all the debug info stuff and then throwing it away but it should be okay minus it taking an extra 20-40min of build time.

**Comment by stgraber** [comment]
The config is now present in the 6.6.2 build available in the repository.
