### ISSUE TITLE
How to get matching linux-modules-extra-(version_number)-generic packages for zabbly ?

### ISSUE THREAD

**Issue by lxj616** [zabbly/linux#7]
Hi, thank you for this amazing repository,

I have `linux-image-6.6.2-zabbly+` installed but I can not find a suitable linux-modules-extra package for drivers

Please help me with some hints how to get this linux-modules-extra package ?

Thanks in advance

**Comment by stgraber** [comment]
That package name is an Ubuntu specific concept. In upstream packaging, all modules are in the image package that you installed.
