### ISSUE TITLE
Kernel 6.6.5 Network Manager Debian Testing 

### ISSUE THREAD

**Issue by arunnabraham** [zabbly/linux#8]
While trying to switch wifi SSID. it got stuck. I rebooted and tried again, which looks the same. 
The I saw while rebooting it was shutting down the newtork services. Error came something related to kernel.

Then I switched to minor version downgrade 6.6.4. Then worked.

**Comment by stgraber** [comment]
What wifi driver are you using?

What do you mean by `it got stuck`? Do you mean the entire system hung and you had to force reboot or do you mean the wifi connection got stuck?

**Comment by arunnabraham** [comment]
![image](https://github.com/zabbly/linux/assets/20944715/da33161b-1e7f-4b57-a3ff-0019de6579bd)

The image above shows my driver.

The system behaves fine and connects my wifi on start. But issue happens when I tried to switch my SSID

It is like when  I switch my SSID the network manager froze, eventually the entire system was nearly unresponsive.

So I saw some hint white restarting some incompatiblity issue (forgot to take note of that) with the current kernel version 6.6.5. So then I switched to the 6.6.4 and that worked fine. 

This behaviour persisted all the session restarts, until I changed the version.

**Comment by stgraber** [comment]
The output of `dmesg` (as root) right after the attempt to switch SSID would probably be useful to figure out what change would have caused this. There are a few wifi related changes between 6.6.4 and 6.6.5 but nothing that's related to Mediatek specifically.

**Comment by arunnabraham** [comment]
![kern_errorjpg](https://github.com/zabbly/linux/assets/20944715/ad47e775-6bba-4f3c-aefa-2ce74d9868c6)
I got this while rebooting

**Comment by arunnabraham** [comment]
Let me know if this has any useful insight

**Comment by stgraber** [comment]
No, that just shows that something is hanging in the kernel, but we're going to need to see the kernel log (`sudo dmesg`) to see what's going on.

**Comment by arunnabraham** [comment]
![deauth](https://github.com/zabbly/linux/assets/20944715/a6fd645e-6f96-4461-9d4d-395ad19f09e6)

I could only get while switching after that dmesg is not working it kind of froze  I think.

**Comment by stgraber** [comment]
Okay, you're going to want to get rid of the `evbug` driver at least to get a cleaner log.

As root, you'll want to run:
```
rmmod evbug
echo "blacklist evbug" > /etc/modprobe.d/blacklist-evbug.conf
update-initramfs -u
```

That will unload the evbug (input device debug driver) and make sure it doesn't get loaded back next time you boot your system.


The one deauth line in your log is still nothing abnormal, so we really need to get the kernel output from when the issue happens as that will include a more useful stacktrace.

Maybe systemd was able to record something, in which case you may be able to get it with `journalctl -k -b-1 -n 500`.

**Comment by arunnabraham** [comment]
Hi @stgraber Sorry I was not avaliable for a while. But many thanks for your work. really appreciate that :)

**Comment by stgraber** [comment]
Linux 6.6.6 is now in the repository.
